
package com.cookiecraftmods.farmhousedecorations.init;

import com.cookiecraftmods.farmhousedecorations.block.*;
import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import com.cookiecraftmods.farmhousedecorations.block.WorkbenchBlock;
import com.cookiecraftmods.farmhousedecorations.block.WineGlassBlock;
import com.cookiecraftmods.farmhousedecorations.block.WineBottleBlock;
import com.cookiecraftmods.farmhousedecorations.block.WardrobeBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.TypewriterBlock;
import com.cookiecraftmods.farmhousedecorations.block.TowelHangerBlock;
import com.cookiecraftmods.farmhousedecorations.block.ToolBoardBlock;
import com.cookiecraftmods.farmhousedecorations.block.TallBookshelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.StandingLampBlock;
import com.cookiecraftmods.farmhousedecorations.block.SofaRightBlock;
import com.cookiecraftmods.farmhousedecorations.block.SofaMiddleBlock;
import com.cookiecraftmods.farmhousedecorations.block.SofaLeftBlock;
import com.cookiecraftmods.farmhousedecorations.block.SmallBathroomMirrorBlock;
import com.cookiecraftmods.farmhousedecorations.block.SingleBedBlock;
import com.cookiecraftmods.farmhousedecorations.block.SeasoningRackBlock;
import com.cookiecraftmods.farmhousedecorations.block.ScreenWood2Block;
import com.cookiecraftmods.farmhousedecorations.block.ScreenWood1Block;
import com.cookiecraftmods.farmhousedecorations.block.ScreenCloth2Block;
import com.cookiecraftmods.farmhousedecorations.block.ScreenCloth1Block;
import com.cookiecraftmods.farmhousedecorations.block.Rug3x3Block;
import com.cookiecraftmods.farmhousedecorations.block.Rug1x3Block;
import com.cookiecraftmods.farmhousedecorations.block.RoundTableBlock;
import com.cookiecraftmods.farmhousedecorations.block.RockingChairBlock;
import com.cookiecraftmods.farmhousedecorations.block.RedWineBottleBlock;
import com.cookiecraftmods.farmhousedecorations.block.RadioBlock;
import com.cookiecraftmods.farmhousedecorations.block.RadiatorBlock;
import com.cookiecraftmods.farmhousedecorations.block.PileOfBooksBlock;
import com.cookiecraftmods.farmhousedecorations.block.PianoWithStoolBlock;
import com.cookiecraftmods.farmhousedecorations.block.PianoBlock;
import com.cookiecraftmods.farmhousedecorations.block.PhoneBlock;
import com.cookiecraftmods.farmhousedecorations.block.NightStandBlock;
import com.cookiecraftmods.farmhousedecorations.block.LiquorCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.LampBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenWallShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenWallCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenSinkBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenHalfwallShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenDrawersBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenCounterBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenCornerWallCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenCornerCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenAntiqueOvenDecoratedBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenAntiqueOvenBlock;
import com.cookiecraftmods.farmhousedecorations.block.KeroseneLanternBlock;
import com.cookiecraftmods.farmhousedecorations.block.GramophoneBlock;
import com.cookiecraftmods.farmhousedecorations.block.FridgeBlock;
import com.cookiecraftmods.farmhousedecorations.block.DresserBlock;
import com.cookiecraftmods.farmhousedecorations.block.DoubleBedBlock;
import com.cookiecraftmods.farmhousedecorations.block.DoorMatBlock;
import com.cookiecraftmods.farmhousedecorations.block.DiningTableSideBlock;
import com.cookiecraftmods.farmhousedecorations.block.DiningTableMiddleBlock;
import com.cookiecraftmods.farmhousedecorations.block.DiningChairBlock;
import com.cookiecraftmods.farmhousedecorations.block.DeskBlock;
import com.cookiecraftmods.farmhousedecorations.block.CuckooClockBlock;
import com.cookiecraftmods.farmhousedecorations.block.CoffeeTableBlock;
import com.cookiecraftmods.farmhousedecorations.block.CoatHangerBlock;
import com.cookiecraftmods.farmhousedecorations.block.CigarBoxBlock;
import com.cookiecraftmods.farmhousedecorations.block.ChainedKeroseneLanternBlock;
import com.cookiecraftmods.farmhousedecorations.block.BigBathroomMirrorBlock;
import com.cookiecraftmods.farmhousedecorations.block.BathtubBlock;
import com.cookiecraftmods.farmhousedecorations.block.BathroomSinkBlock;
import com.cookiecraftmods.farmhousedecorations.block.BathroomCounterBlock;
import com.cookiecraftmods.farmhousedecorations.block.BathroomCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.AntiqueOvenBlock;
import com.cookiecraftmods.farmhousedecorations.block.AncientTVWithLegsBlock;
import com.cookiecraftmods.farmhousedecorations.block.AncientTVBlock;
import com.cookiecraftmods.farmhousedecorations.block.AcousticGuitarBlock;
import com.cookiecraftmods.farmhousedecorations.FarmhouseDecorationsMod;

public class FarmhouseDecorationsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FarmhouseDecorationsMod.MODID);
	public static final RegistryObject<Block> LIQUOR_CABINET = REGISTRY.register("liquor_cabinet", () -> new LiquorCabinetBlock());
	public static final RegistryObject<Block> KEROSENE_LANTERN = REGISTRY.register("kerosene_lantern", () -> new KeroseneLanternBlock());
	public static final RegistryObject<Block> ACOUSTIC_GUITAR = REGISTRY.register("acoustic_guitar", () -> new AcousticGuitarBlock());
	public static final RegistryObject<Block> DOUBLE_BED = REGISTRY.register("double_bed", () -> new DoubleBedBlock());
	public static final RegistryObject<Block> ANTIQUE_OVEN = REGISTRY.register("antique_oven", () -> new AntiqueOvenBlock());
	public static final RegistryObject<Block> SINGLE_BED = REGISTRY.register("single_bed", () -> new SingleBedBlock());
	public static final RegistryObject<Block> TALL_BOOKSHELF = REGISTRY.register("tall_bookshelf", () -> new TallBookshelfBlock());
	public static final RegistryObject<Block> WINE_BOTTLE = REGISTRY.register("wine_bottle", () -> new WineBottleBlock());
	public static final RegistryObject<Block> RED_WINE_BOTTLE = REGISTRY.register("red_wine_bottle", () -> new RedWineBottleBlock());
	public static final RegistryObject<Block> CUCKOO_CLOCK = REGISTRY.register("cuckoo_clock", () -> new CuckooClockBlock());
	public static final RegistryObject<Block> DINING_CHAIR = REGISTRY.register("dining_chair", () -> new DiningChairBlock());
	public static final RegistryObject<Block> DINING_TABLE_SIDE = REGISTRY.register("dining_table_side", () -> new DiningTableSideBlock());
	public static final RegistryObject<Block> DINING_TABLE_MIDDLE = REGISTRY.register("dining_table_middle", () -> new DiningTableMiddleBlock());
	public static final RegistryObject<Block> DRESSER = REGISTRY.register("dresser", () -> new DresserBlock());
	public static final RegistryObject<Block> NIGHT_STAND = REGISTRY.register("night_stand", () -> new NightStandBlock());
	public static final RegistryObject<Block> PIANO = REGISTRY.register("piano", () -> new PianoBlock());
	public static final RegistryObject<Block> PIANO_WITH_STOOL = REGISTRY.register("piano_with_stool", () -> new PianoWithStoolBlock());
	public static final RegistryObject<Block> ROCKING_CHAIR = REGISTRY.register("rocking_chair", () -> new RockingChairBlock());
	public static final RegistryObject<Block> ROUND_TABLE = REGISTRY.register("round_table", () -> new RoundTableBlock());
	public static final RegistryObject<Block> STANDING_LAMP = REGISTRY.register("standing_lamp", () -> new StandingLampBlock());
	public static final RegistryObject<Block> CHAINED_KEROSENE_LANTERN = REGISTRY.register("chained_kerosene_lantern", () -> new ChainedKeroseneLanternBlock());
	public static final RegistryObject<Block> SOFA_LEFT = REGISTRY.register("sofa_left", () -> new SofaLeftBlock());
	public static final RegistryObject<Block> SOFA_RIGHT = REGISTRY.register("sofa_right", () -> new SofaRightBlock());
	public static final RegistryObject<Block> SOFA_MIDDLE = REGISTRY.register("sofa_middle", () -> new SofaMiddleBlock());
	public static final RegistryObject<Block> TOOL_BOARD = REGISTRY.register("tool_board", () -> new ToolBoardBlock());
	public static final RegistryObject<Block> WARDROBE = REGISTRY.register("wardrobe", () -> new WardrobeBlock());
	public static final RegistryObject<Block> COAT_HANGER = REGISTRY.register("coat_hanger", () -> new CoatHangerBlock());
	public static final RegistryObject<Block> WINE_GLASS = REGISTRY.register("wine_glass", () -> new WineGlassBlock());
	public static final RegistryObject<Block> WORKBENCH = REGISTRY.register("workbench", () -> new WorkbenchBlock());
	public static final RegistryObject<Block> KITCHEN_ANTIQUE_OVEN = REGISTRY.register("kitchen_antique_oven", () -> new KitchenAntiqueOvenBlock());
	public static final RegistryObject<Block> KITCHEN_ANTIQUE_OVEN_DECORATED = REGISTRY.register("kitchen_antique_oven_decorated", () -> new KitchenAntiqueOvenDecoratedBlock());
	public static final RegistryObject<Block> KITCHEN_COUNTER = REGISTRY.register("kitchen_counter", () -> new KitchenCounterBlock());
	public static final RegistryObject<Block> KITCHEN_CORNER_CABINET = REGISTRY.register("kitchen_corner_cabinet", () -> new KitchenCornerCabinetBlock());
	public static final RegistryObject<Block> KITCHEN_DRAWERS = REGISTRY.register("kitchen_drawers", () -> new KitchenDrawersBlock());
	public static final RegistryObject<Block> KITCHEN_HALFWALL_SHELF = REGISTRY.register("kitchen_halfwall_shelf", () -> new KitchenHalfwallShelfBlock());
	public static final RegistryObject<Block> KITCHEN_SINK = REGISTRY.register("kitchen_sink", () -> new KitchenSinkBlock());
	public static final RegistryObject<Block> KITCHEN_WALL_CABINET = REGISTRY.register("kitchen_wall_cabinet", () -> new KitchenWallCabinetBlock());
	public static final RegistryObject<Block> KITCHEN_CORNER_WALL_CABINET = REGISTRY.register("kitchen_corner_wall_cabinet", () -> new KitchenCornerWallCabinetBlock());
	public static final RegistryObject<Block> KITCHEN_WALL_SHELF = REGISTRY.register("kitchen_wall_shelf", () -> new KitchenWallShelfBlock());
	public static final RegistryObject<Block> BATHTUB = REGISTRY.register("bathtub", () -> new BathtubBlock());
	public static final RegistryObject<Block> BATHROOM_CABINET = REGISTRY.register("bathroom_cabinet", () -> new BathroomCabinetBlock());
	public static final RegistryObject<Block> BATHROOM_COUNTER = REGISTRY.register("bathroom_counter", () -> new BathroomCounterBlock());
	public static final RegistryObject<Block> BATHROOM_SINK = REGISTRY.register("bathroom_sink", () -> new BathroomSinkBlock());
	public static final RegistryObject<Block> BIG_BATHROOM_MIRROR = REGISTRY.register("big_bathroom_mirror", () -> new BigBathroomMirrorBlock());
	public static final RegistryObject<Block> SMALL_BATHROOM_MIRROR = REGISTRY.register("small_bathroom_mirror", () -> new SmallBathroomMirrorBlock());
	public static final RegistryObject<Block> TOWEL_HANGER = REGISTRY.register("towel_hanger", () -> new TowelHangerBlock());
	public static final RegistryObject<Block> FRIDGE = REGISTRY.register("fridge", () -> new FridgeBlock());
	public static final RegistryObject<Block> LAMP = REGISTRY.register("lamp", () -> new LampBlock());
	public static final RegistryObject<Block> CIGAR_BOX = REGISTRY.register("cigar_box", () -> new CigarBoxBlock());
	public static final RegistryObject<Block> GRAMOPHONE = REGISTRY.register("gramophone", () -> new GramophoneBlock());
	public static final RegistryObject<Block> RADIATOR = REGISTRY.register("radiator", () -> new RadiatorBlock());
	public static final RegistryObject<Block> PHONE = REGISTRY.register("phone", () -> new PhoneBlock());
	public static final RegistryObject<Block> ANCIENT_TV_WITH_LEGS = REGISTRY.register("ancient_tv_with_legs", () -> new AncientTVWithLegsBlock());
	public static final RegistryObject<Block> ANCIENT_TV = REGISTRY.register("ancient_tv", () -> new AncientTVBlock());
	public static final RegistryObject<Block> COFFEE_TABLE = REGISTRY.register("coffee_table", () -> new CoffeeTableBlock());
	public static final RegistryObject<Block> PILE_OF_BOOKS = REGISTRY.register("pile_of_books", () -> new PileOfBooksBlock());
	public static final RegistryObject<Block> DESK = REGISTRY.register("desk", () -> new DeskBlock());
	public static final RegistryObject<Block> DOOR_MAT = REGISTRY.register("door_mat", () -> new DoorMatBlock());
	public static final RegistryObject<Block> SCREEN_CLOTH_1 = REGISTRY.register("screen_cloth_1", () -> new ScreenCloth1Block());
	public static final RegistryObject<Block> SCREEN_CLOTH_2 = REGISTRY.register("screen_cloth_2", () -> new ScreenCloth2Block());
	public static final RegistryObject<Block> SCREEN_WOOD_1 = REGISTRY.register("screen_wood_1", () -> new ScreenWood1Block());
	public static final RegistryObject<Block> SCREEN_WOOD_2 = REGISTRY.register("screen_wood_2", () -> new ScreenWood2Block());
	public static final RegistryObject<Block> RADIO = REGISTRY.register("radio", () -> new RadioBlock());
	public static final RegistryObject<Block> RUG_1X_3 = REGISTRY.register("rug_1x_3", () -> new Rug1x3Block());
	public static final RegistryObject<Block> RUG_3X_3 = REGISTRY.register("rug_3x_3", () -> new Rug3x3Block());
	public static final RegistryObject<Block> SEASONING_RACK = REGISTRY.register("seasoning_rack", () -> new SeasoningRackBlock());
	public static final RegistryObject<Block> TYPEWRITER = REGISTRY.register("typewriter", () -> new TypewriterBlock());
	public static final RegistryObject<Block> WALL_SHELF = REGISTRY.register("wall_shelf", () -> new WallShelfBlock());
	public static final RegistryObject<Block> ANCIENT_TV_STAND = REGISTRY.register("ancient_tv_stand", () -> new AncientTVStandBlock());
	public static final RegistryObject<Block> CEILING_LAMP = REGISTRY.register("ceiling_lamp", () -> new CeilingLampBlock());
	public static final RegistryObject<Block> CHANDELIER = REGISTRY.register("chandelier", () -> new ChandelierBlock());
	public static final RegistryObject<Block> CURTAIN_ROD = REGISTRY.register("curtain_rod", () -> new CurtainRodBlock());
	public static final RegistryObject<Block> CURTAINS_1W = REGISTRY.register("curtains_1w", () -> new Curtains1wBlock());
	public static final RegistryObject<Block> CURTAINS_1W_LONG = REGISTRY.register("curtains_1w_long", () -> new Curtains1wLongBlock());
	public static final RegistryObject<Block> CURTAINS_LEFT = REGISTRY.register("curtains_left", () -> new CurtainsLeftBlock());
	public static final RegistryObject<Block> CURTAINS_LEFT_LONG = REGISTRY.register("curtains_left_long", () -> new CurtainsLeftLongBlock());
	public static final RegistryObject<Block> CURTAINS_RIGHT = REGISTRY.register("curtains_right", () -> new CurtainsRightBlock());
	public static final RegistryObject<Block> CURTAINS_RIGHT_LONG = REGISTRY.register("curtains_right_long", () -> new CurtainsRightLongBlock());
	public static final RegistryObject<Block> HANGING_SHELF = REGISTRY.register("hanging_shelf", () -> new HangingShelfBlock());
	public static final RegistryObject<Block> OLD_BATHROOM_RADIATOR = REGISTRY.register("old_bathroom_radiator", () -> new OldBathroomRadiatorBlock());
	public static final RegistryObject<Block> WALL_TELEPHONE = REGISTRY.register("wall_telephone", () -> new WallTelephoneBlock());
	public static final RegistryObject<Block> TOILET = REGISTRY.register("toilet", () -> new ToiletBlock());
	public static final RegistryObject<Block> WALL_LAMP_CANDLE = REGISTRY.register("wall_lamp_candle", () -> new WallLampCandleBlock());
	public static final RegistryObject<Block> WALL_SHADE = REGISTRY.register("wall_shade", () -> new WallShadeBlock());
	public static final RegistryObject<Block> WINDOW_BLINDS = REGISTRY.register("window_blinds", () -> new WindowBlindsBlock());
	public static final RegistryObject<Block> WINDOW_BLINDS_LONG = REGISTRY.register("window_blinds_long", () -> new WindowBlindsLongBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
