plugins {
    id 'fabric-loom' version '1.6.1'
}

apply from: '../../gradle/common.gradle'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(project.java_version))
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}
