org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.home=C:\\Program Files\\Java\\jdk-25.0.4

minecraft_version=26.3
loader_version=0.19.5
fabric_version=0.162.0+26.3
java_version=25
loader_name=fabric
