package com.cookiecraftmods.farmhousedecorations.init;

import com.cookiecraftmods.farmhousedecorations.block.AncientTVStandBlock;
import com.cookiecraftmods.farmhousedecorations.block.CeilingLampBlock;
import com.cookiecraftmods.farmhousedecorations.block.ChandelierBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainRodBlock;
import com.cookiecraftmods.farmhousedecorations.block.Curtains1wBlock;
import com.cookiecraftmods.farmhousedecorations.block.Curtains1wLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsLeftBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsLeftLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsRightBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsRightLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.HangingShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.OldBathroomRadiatorBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallTelephoneBlock;
import com.cookiecraftmods.farmhousedecorations.block.ToiletBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallLampCandleBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallShadeBlock;
import com.cookiecraftmods.farmhousedecorations.block.WindowBlindsBlock;
import com.cookiecraftmods.farmhousedecorations.block.WindowBlindsLongBlock;

import java.util.function.Supplier;

import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.block.Block;

import com.cookiecraftmods.farmhousedecorations.FarmhouseDecorationsMod;
import com.cookiecraftmods.farmhousedecorations.block.AcousticGuitarBlock;
import com.cookiecraftmods.farmhousedecorations.block.AncientTVBlock;
import com.cookiecraftmods.farmhousedecorations.block.AncientTVWithLegsBlock;
import com.cookiecraftmods.farmhousedecorations.block.AntiqueOvenBlock;
import com.cookiecraftmods.farmhousedecorations.block.BathroomCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.BathroomCounterBlock;
import com.cookiecraftmods.farmhousedecorations.block.BathroomSinkBlock;
import com.cookiecraftmods.farmhousedecorations.block.BathtubBlock;
import com.cookiecraftmods.farmhousedecorations.block.BigBathroomMirrorBlock;
import com.cookiecraftmods.farmhousedecorations.block.ChainedKeroseneLanternBlock;
import com.cookiecraftmods.farmhousedecorations.block.CigarBoxBlock;
import com.cookiecraftmods.farmhousedecorations.block.CoatHangerBlock;
import com.cookiecraftmods.farmhousedecorations.block.CoffeeTableBlock;
import com.cookiecraftmods.farmhousedecorations.block.CuckooClockBlock;
import com.cookiecraftmods.farmhousedecorations.block.DeskBlock;
import com.cookiecraftmods.farmhousedecorations.block.DiningChairBlock;
import com.cookiecraftmods.farmhousedecorations.block.DiningTableMiddleBlock;
import com.cookiecraftmods.farmhousedecorations.block.DiningTableSideBlock;
import com.cookiecraftmods.farmhousedecorations.block.DoorMatBlock;
import com.cookiecraftmods.farmhousedecorations.block.DoubleBedBlock;
import com.cookiecraftmods.farmhousedecorations.block.DresserBlock;
import com.cookiecraftmods.farmhousedecorations.block.FridgeBlock;
import com.cookiecraftmods.farmhousedecorations.block.GramophoneBlock;
import com.cookiecraftmods.farmhousedecorations.block.KeroseneLanternBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenAntiqueOvenBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenAntiqueOvenDecoratedBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenCornerCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenCornerWallCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenCounterBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenDrawersBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenHalfwallShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenSinkBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenWallCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.KitchenWallShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.LampBlock;
import com.cookiecraftmods.farmhousedecorations.block.LiquorCabinetBlock;
import com.cookiecraftmods.farmhousedecorations.block.NightStandBlock;
import com.cookiecraftmods.farmhousedecorations.block.PhoneBlock;
import com.cookiecraftmods.farmhousedecorations.block.PianoBlock;
import com.cookiecraftmods.farmhousedecorations.block.PianoWithStoolBlock;
import com.cookiecraftmods.farmhousedecorations.block.PileOfBooksBlock;
import com.cookiecraftmods.farmhousedecorations.block.RadiatorBlock;
import com.cookiecraftmods.farmhousedecorations.block.RadioBlock;
import com.cookiecraftmods.farmhousedecorations.block.RedWineBottleBlock;
import com.cookiecraftmods.farmhousedecorations.block.RockingChairBlock;
import com.cookiecraftmods.farmhousedecorations.block.RoundTableBlock;
import com.cookiecraftmods.farmhousedecorations.block.Rug1x3Block;
import com.cookiecraftmods.farmhousedecorations.block.Rug3x3Block;
import com.cookiecraftmods.farmhousedecorations.block.ScreenCloth1Block;
import com.cookiecraftmods.farmhousedecorations.block.ScreenCloth2Block;
import com.cookiecraftmods.farmhousedecorations.block.ScreenWood1Block;
import com.cookiecraftmods.farmhousedecorations.block.ScreenWood2Block;
import com.cookiecraftmods.farmhousedecorations.block.SeasoningRackBlock;
import com.cookiecraftmods.farmhousedecorations.block.SingleBedBlock;
import com.cookiecraftmods.farmhousedecorations.block.SmallBathroomMirrorBlock;
import com.cookiecraftmods.farmhousedecorations.block.SofaLeftBlock;
import com.cookiecraftmods.farmhousedecorations.block.SofaMiddleBlock;
import com.cookiecraftmods.farmhousedecorations.block.SofaRightBlock;
import com.cookiecraftmods.farmhousedecorations.block.StandingLampBlock;
import com.cookiecraftmods.farmhousedecorations.block.TallBookshelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.ToolBoardBlock;
import com.cookiecraftmods.farmhousedecorations.block.TowelHangerBlock;
import com.cookiecraftmods.farmhousedecorations.block.TypewriterBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.WardrobeBlock;
import com.cookiecraftmods.farmhousedecorations.block.WineBottleBlock;
import com.cookiecraftmods.farmhousedecorations.block.WineGlassBlock;
import com.cookiecraftmods.farmhousedecorations.block.WorkbenchBlock;

public class FarmhouseDecorationsModBlocks {
	public static final Block LIQUOR_CABINET = register("liquor_cabinet", LiquorCabinetBlock::new);
	public static final Block KEROSENE_LANTERN = register("kerosene_lantern", KeroseneLanternBlock::new);
	public static final Block ACOUSTIC_GUITAR = register("acoustic_guitar", AcousticGuitarBlock::new);
	public static final Block DOUBLE_BED = register("double_bed", DoubleBedBlock::new);
	public static final Block ANTIQUE_OVEN = register("antique_oven", AntiqueOvenBlock::new);
	public static final Block SINGLE_BED = register("single_bed", SingleBedBlock::new);
	public static final Block TALL_BOOKSHELF = register("tall_bookshelf", TallBookshelfBlock::new);
	public static final Block WINE_BOTTLE = register("wine_bottle", WineBottleBlock::new);
	public static final Block RED_WINE_BOTTLE = register("red_wine_bottle", RedWineBottleBlock::new);
	public static final Block CUCKOO_CLOCK = register("cuckoo_clock", CuckooClockBlock::new);
	public static final Block DINING_CHAIR = register("dining_chair", DiningChairBlock::new);
	public static final Block DINING_TABLE_SIDE = register("dining_table_side", DiningTableSideBlock::new);
	public static final Block DINING_TABLE_MIDDLE = register("dining_table_middle", DiningTableMiddleBlock::new);
	public static final Block DRESSER = register("dresser", DresserBlock::new);
	public static final Block NIGHT_STAND = register("night_stand", NightStandBlock::new);
	public static final Block PIANO = register("piano", PianoBlock::new);
	public static final Block PIANO_WITH_STOOL = register("piano_with_stool", PianoWithStoolBlock::new);
	public static final Block ROCKING_CHAIR = register("rocking_chair", RockingChairBlock::new);
	public static final Block ROUND_TABLE = register("round_table", RoundTableBlock::new);
	public static final Block STANDING_LAMP = register("standing_lamp", StandingLampBlock::new);
	public static final Block CHAINED_KEROSENE_LANTERN = register("chained_kerosene_lantern", ChainedKeroseneLanternBlock::new);
	public static final Block SOFA_LEFT = register("sofa_left", SofaLeftBlock::new);
	public static final Block SOFA_RIGHT = register("sofa_right", SofaRightBlock::new);
	public static final Block SOFA_MIDDLE = register("sofa_middle", SofaMiddleBlock::new);
	public static final Block TOOL_BOARD = register("tool_board", ToolBoardBlock::new);
	public static final Block WARDROBE = register("wardrobe", WardrobeBlock::new);
	public static final Block COAT_HANGER = register("coat_hanger", CoatHangerBlock::new);
	public static final Block WINE_GLASS = register("wine_glass", WineGlassBlock::new);
	public static final Block WORKBENCH = register("workbench", WorkbenchBlock::new);
	public static final Block KITCHEN_ANTIQUE_OVEN = register("kitchen_antique_oven", KitchenAntiqueOvenBlock::new);
	public static final Block KITCHEN_ANTIQUE_OVEN_DECORATED = register("kitchen_antique_oven_decorated", KitchenAntiqueOvenDecoratedBlock::new);
	public static final Block KITCHEN_COUNTER = register("kitchen_counter", KitchenCounterBlock::new);
	public static final Block KITCHEN_CORNER_CABINET = register("kitchen_corner_cabinet", KitchenCornerCabinetBlock::new);
	public static final Block KITCHEN_DRAWERS = register("kitchen_drawers", KitchenDrawersBlock::new);
	public static final Block KITCHEN_HALFWALL_SHELF = register("kitchen_halfwall_shelf", KitchenHalfwallShelfBlock::new);
	public static final Block KITCHEN_SINK = register("kitchen_sink", KitchenSinkBlock::new);
	public static final Block KITCHEN_WALL_CABINET = register("kitchen_wall_cabinet", KitchenWallCabinetBlock::new);
	public static final Block KITCHEN_CORNER_WALL_CABINET = register("kitchen_corner_wall_cabinet", KitchenCornerWallCabinetBlock::new);
	public static final Block KITCHEN_WALL_SHELF = register("kitchen_wall_shelf", KitchenWallShelfBlock::new);
	public static final Block BATHTUB = register("bathtub", BathtubBlock::new);
	public static final Block BATHROOM_CABINET = register("bathroom_cabinet", BathroomCabinetBlock::new);
	public static final Block BATHROOM_COUNTER = register("bathroom_counter", BathroomCounterBlock::new);
	public static final Block BATHROOM_SINK = register("bathroom_sink", BathroomSinkBlock::new);
	public static final Block BIG_BATHROOM_MIRROR = register("big_bathroom_mirror", BigBathroomMirrorBlock::new);
	public static final Block SMALL_BATHROOM_MIRROR = register("small_bathroom_mirror", SmallBathroomMirrorBlock::new);
	public static final Block TOWEL_HANGER = register("towel_hanger", TowelHangerBlock::new);
	public static final Block FRIDGE = register("fridge", FridgeBlock::new);
	public static final Block LAMP = register("lamp", LampBlock::new);
	public static final Block CIGAR_BOX = register("cigar_box", CigarBoxBlock::new);
	public static final Block GRAMOPHONE = register("gramophone", GramophoneBlock::new);
	public static final Block RADIATOR = register("radiator", RadiatorBlock::new);
	public static final Block PHONE = register("phone", PhoneBlock::new);
	public static final Block ANCIENT_TV_WITH_LEGS = register("ancient_tv_with_legs", AncientTVWithLegsBlock::new);
	public static final Block ANCIENT_TV = register("ancient_tv", AncientTVBlock::new);
	public static final Block COFFEE_TABLE = register("coffee_table", CoffeeTableBlock::new);
	public static final Block PILE_OF_BOOKS = register("pile_of_books", PileOfBooksBlock::new);
	public static final Block DESK = register("desk", DeskBlock::new);
	public static final Block DOOR_MAT = register("door_mat", DoorMatBlock::new);
	public static final Block SCREEN_CLOTH_1 = register("screen_cloth_1", ScreenCloth1Block::new);
	public static final Block SCREEN_CLOTH_2 = register("screen_cloth_2", ScreenCloth2Block::new);
	public static final Block SCREEN_WOOD_1 = register("screen_wood_1", ScreenWood1Block::new);
	public static final Block SCREEN_WOOD_2 = register("screen_wood_2", ScreenWood2Block::new);
	public static final Block RADIO = register("radio", RadioBlock::new);
	public static final Block RUG_1X_3 = register("rug_1x_3", Rug1x3Block::new);
	public static final Block RUG_3X_3 = register("rug_3x_3", Rug3x3Block::new);
	public static final Block SEASONING_RACK = register("seasoning_rack", SeasoningRackBlock::new);
	public static final Block TYPEWRITER = register("typewriter", TypewriterBlock::new);
	public static final Block WALL_SHELF = register("wall_shelf", WallShelfBlock::new);
	public static final Block ANCIENT_TV_STAND = register("ancient_tv_stand", AncientTVStandBlock::new);
	public static final Block CEILING_LAMP = register("ceiling_lamp", CeilingLampBlock::new);
	public static final Block CHANDELIER = register("chandelier", ChandelierBlock::new);
	public static final Block CURTAIN_ROD = register("curtain_rod", CurtainRodBlock::new);
	public static final Block CURTAINS_1W = register("curtains_1w", Curtains1wBlock::new);
	public static final Block CURTAINS_1W_LONG = register("curtains_1w_long", Curtains1wLongBlock::new);
	public static final Block CURTAINS_LEFT = register("curtains_left", CurtainsLeftBlock::new);
	public static final Block CURTAINS_LEFT_LONG = register("curtains_left_long", CurtainsLeftLongBlock::new);
	public static final Block CURTAINS_RIGHT = register("curtains_right", CurtainsRightBlock::new);
	public static final Block CURTAINS_RIGHT_LONG = register("curtains_right_long", CurtainsRightLongBlock::new);
	public static final Block HANGING_SHELF = register("hanging_shelf", HangingShelfBlock::new);
	public static final Block OLD_BATHROOM_RADIATOR = register("old_bathroom_radiator", OldBathroomRadiatorBlock::new);
	public static final Block WALL_TELEPHONE = register("wall_telephone", WallTelephoneBlock::new);
	public static final Block TOILET = register("toilet", ToiletBlock::new);
	public static final Block WALL_LAMP_CANDLE = register("wall_lamp_candle", WallLampCandleBlock::new);
	public static final Block WALL_SHADE = register("wall_shade", WallShadeBlock::new);
	public static final Block WINDOW_BLINDS = register("window_blinds", WindowBlindsBlock::new);
	public static final Block WINDOW_BLINDS_LONG = register("window_blinds_long", WindowBlindsLongBlock::new);
	private FarmhouseDecorationsModBlocks() {
	}

	public static void init() {
	}

	private static <T extends Block> T register(String id, Supplier<T> factory) {
		return Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(FarmhouseDecorationsMod.MODID, id), factory.get());
	}
}
