package com.cookiecraftmods.farmhousedecorations.init;

import com.cookiecraftmods.farmhousedecorations.block.AncientTVStandBlock;
import com.cookiecraftmods.farmhousedecorations.block.CeilingLampBlock;
import com.cookiecraftmods.farmhousedecorations.block.ChandelierBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainRodBlock;
import com.cookiecraftmods.farmhousedecorations.block.Curtains1wBlock;
import com.cookiecraftmods.farmhousedecorations.block.Curtains1wLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsLeftBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsLeftLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsRightBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsRightLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.HangingShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.OldBathroomRadiatorBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallTelephoneBlock;
import com.cookiecraftmods.farmhousedecorations.block.ToiletBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallLampCandleBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallShadeBlock;
import com.cookiecraftmods.farmhousedecorations.block.WindowBlindsBlock;
import com.cookiecraftmods.farmhousedecorations.block.WindowBlindsLongBlock;

import com.cookiecraftmods.farmhousedecorations.FarmhouseDecorationsMod;
import com.cookiecraftmods.farmhousedecorations.block.*;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

public final class FarmhouseDecorationsModBlocks {
    public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(FarmhouseDecorationsMod.MODID);
    public static final DeferredBlock<Block> LIQUOR_CABINET = REGISTRY.register("liquor_cabinet", () -> new LiquorCabinetBlock());
    public static final DeferredBlock<Block> KEROSENE_LANTERN = REGISTRY.register("kerosene_lantern", () -> new KeroseneLanternBlock());
    public static final DeferredBlock<Block> ACOUSTIC_GUITAR = REGISTRY.register("acoustic_guitar", () -> new AcousticGuitarBlock());
    public static final DeferredBlock<Block> DOUBLE_BED = REGISTRY.register("double_bed", () -> new DoubleBedBlock());
    public static final DeferredBlock<Block> ANTIQUE_OVEN = REGISTRY.register("antique_oven", () -> new AntiqueOvenBlock());
    public static final DeferredBlock<Block> SINGLE_BED = REGISTRY.register("single_bed", () -> new SingleBedBlock());
    public static final DeferredBlock<Block> TALL_BOOKSHELF = REGISTRY.register("tall_bookshelf", () -> new TallBookshelfBlock());
    public static final DeferredBlock<Block> WINE_BOTTLE = REGISTRY.register("wine_bottle", () -> new WineBottleBlock());
    public static final DeferredBlock<Block> RED_WINE_BOTTLE = REGISTRY.register("red_wine_bottle", () -> new RedWineBottleBlock());
    public static final DeferredBlock<Block> CUCKOO_CLOCK = REGISTRY.register("cuckoo_clock", () -> new CuckooClockBlock());
    public static final DeferredBlock<Block> DINING_CHAIR = REGISTRY.register("dining_chair", () -> new DiningChairBlock());
    public static final DeferredBlock<Block> DINING_TABLE_SIDE = REGISTRY.register("dining_table_side", () -> new DiningTableSideBlock());
    public static final DeferredBlock<Block> DINING_TABLE_MIDDLE = REGISTRY.register("dining_table_middle", () -> new DiningTableMiddleBlock());
    public static final DeferredBlock<Block> DRESSER = REGISTRY.register("dresser", () -> new DresserBlock());
    public static final DeferredBlock<Block> NIGHT_STAND = REGISTRY.register("night_stand", () -> new NightStandBlock());
    public static final DeferredBlock<Block> PIANO = REGISTRY.register("piano", () -> new PianoBlock());
    public static final DeferredBlock<Block> PIANO_WITH_STOOL = REGISTRY.register("piano_with_stool", () -> new PianoWithStoolBlock());
    public static final DeferredBlock<Block> ROCKING_CHAIR = REGISTRY.register("rocking_chair", () -> new RockingChairBlock());
    public static final DeferredBlock<Block> ROUND_TABLE = REGISTRY.register("round_table", () -> new RoundTableBlock());
    public static final DeferredBlock<Block> STANDING_LAMP = REGISTRY.register("standing_lamp", () -> new StandingLampBlock());
    public static final DeferredBlock<Block> CHAINED_KEROSENE_LANTERN = REGISTRY.register("chained_kerosene_lantern", () -> new ChainedKeroseneLanternBlock());
    public static final DeferredBlock<Block> SOFA_LEFT = REGISTRY.register("sofa_left", () -> new SofaLeftBlock());
    public static final DeferredBlock<Block> SOFA_RIGHT = REGISTRY.register("sofa_right", () -> new SofaRightBlock());
    public static final DeferredBlock<Block> SOFA_MIDDLE = REGISTRY.register("sofa_middle", () -> new SofaMiddleBlock());
    public static final DeferredBlock<Block> TOOL_BOARD = REGISTRY.register("tool_board", () -> new ToolBoardBlock());
    public static final DeferredBlock<Block> WARDROBE = REGISTRY.register("wardrobe", () -> new WardrobeBlock());
    public static final DeferredBlock<Block> COAT_HANGER = REGISTRY.register("coat_hanger", () -> new CoatHangerBlock());
    public static final DeferredBlock<Block> WINE_GLASS = REGISTRY.register("wine_glass", () -> new WineGlassBlock());
    public static final DeferredBlock<Block> WORKBENCH = REGISTRY.register("workbench", () -> new WorkbenchBlock());
    public static final DeferredBlock<Block> KITCHEN_ANTIQUE_OVEN = REGISTRY.register("kitchen_antique_oven", () -> new KitchenAntiqueOvenBlock());
    public static final DeferredBlock<Block> KITCHEN_ANTIQUE_OVEN_DECORATED = REGISTRY.register("kitchen_antique_oven_decorated", () -> new KitchenAntiqueOvenDecoratedBlock());
    public static final DeferredBlock<Block> KITCHEN_COUNTER = REGISTRY.register("kitchen_counter", () -> new KitchenCounterBlock());
    public static final DeferredBlock<Block> KITCHEN_CORNER_CABINET = REGISTRY.register("kitchen_corner_cabinet", () -> new KitchenCornerCabinetBlock());
    public static final DeferredBlock<Block> KITCHEN_DRAWERS = REGISTRY.register("kitchen_drawers", () -> new KitchenDrawersBlock());
    public static final DeferredBlock<Block> KITCHEN_HALFWALL_SHELF = REGISTRY.register("kitchen_halfwall_shelf", () -> new KitchenHalfwallShelfBlock());
    public static final DeferredBlock<Block> KITCHEN_SINK = REGISTRY.register("kitchen_sink", () -> new KitchenSinkBlock());
    public static final DeferredBlock<Block> KITCHEN_WALL_CABINET = REGISTRY.register("kitchen_wall_cabinet", () -> new KitchenWallCabinetBlock());
    public static final DeferredBlock<Block> KITCHEN_CORNER_WALL_CABINET = REGISTRY.register("kitchen_corner_wall_cabinet", () -> new KitchenCornerWallCabinetBlock());
    public static final DeferredBlock<Block> KITCHEN_WALL_SHELF = REGISTRY.register("kitchen_wall_shelf", () -> new KitchenWallShelfBlock());
    public static final DeferredBlock<Block> BATHTUB = REGISTRY.register("bathtub", () -> new BathtubBlock());
    public static final DeferredBlock<Block> BATHROOM_CABINET = REGISTRY.register("bathroom_cabinet", () -> new BathroomCabinetBlock());
    public static final DeferredBlock<Block> BATHROOM_COUNTER = REGISTRY.register("bathroom_counter", () -> new BathroomCounterBlock());
    public static final DeferredBlock<Block> BATHROOM_SINK = REGISTRY.register("bathroom_sink", () -> new BathroomSinkBlock());
    public static final DeferredBlock<Block> BIG_BATHROOM_MIRROR = REGISTRY.register("big_bathroom_mirror", () -> new BigBathroomMirrorBlock());
    public static final DeferredBlock<Block> SMALL_BATHROOM_MIRROR = REGISTRY.register("small_bathroom_mirror", () -> new SmallBathroomMirrorBlock());
    public static final DeferredBlock<Block> TOWEL_HANGER = REGISTRY.register("towel_hanger", () -> new TowelHangerBlock());
    public static final DeferredBlock<Block> FRIDGE = REGISTRY.register("fridge", () -> new FridgeBlock());
    public static final DeferredBlock<Block> LAMP = REGISTRY.register("lamp", () -> new LampBlock());
    public static final DeferredBlock<Block> CIGAR_BOX = REGISTRY.register("cigar_box", () -> new CigarBoxBlock());
    public static final DeferredBlock<Block> GRAMOPHONE = REGISTRY.register("gramophone", () -> new GramophoneBlock());
    public static final DeferredBlock<Block> RADIATOR = REGISTRY.register("radiator", () -> new RadiatorBlock());
    public static final DeferredBlock<Block> PHONE = REGISTRY.register("phone", () -> new PhoneBlock());
    public static final DeferredBlock<Block> ANCIENT_TV_WITH_LEGS = REGISTRY.register("ancient_tv_with_legs", () -> new AncientTVWithLegsBlock());
    public static final DeferredBlock<Block> ANCIENT_TV = REGISTRY.register("ancient_tv", () -> new AncientTVBlock());
    public static final DeferredBlock<Block> COFFEE_TABLE = REGISTRY.register("coffee_table", () -> new CoffeeTableBlock());
    public static final DeferredBlock<Block> PILE_OF_BOOKS = REGISTRY.register("pile_of_books", () -> new PileOfBooksBlock());
    public static final DeferredBlock<Block> DESK = REGISTRY.register("desk", () -> new DeskBlock());
    public static final DeferredBlock<Block> DOOR_MAT = REGISTRY.register("door_mat", () -> new DoorMatBlock());
    public static final DeferredBlock<Block> SCREEN_CLOTH_1 = REGISTRY.register("screen_cloth_1", () -> new ScreenCloth1Block());
    public static final DeferredBlock<Block> SCREEN_CLOTH_2 = REGISTRY.register("screen_cloth_2", () -> new ScreenCloth2Block());
    public static final DeferredBlock<Block> SCREEN_WOOD_1 = REGISTRY.register("screen_wood_1", () -> new ScreenWood1Block());
    public static final DeferredBlock<Block> SCREEN_WOOD_2 = REGISTRY.register("screen_wood_2", () -> new ScreenWood2Block());
    public static final DeferredBlock<Block> RADIO = REGISTRY.register("radio", () -> new RadioBlock());
    public static final DeferredBlock<Block> RUG_1X_3 = REGISTRY.register("rug_1x_3", () -> new Rug1x3Block());
    public static final DeferredBlock<Block> RUG_3X_3 = REGISTRY.register("rug_3x_3", () -> new Rug3x3Block());
    public static final DeferredBlock<Block> SEASONING_RACK = REGISTRY.register("seasoning_rack", () -> new SeasoningRackBlock());
    public static final DeferredBlock<Block> TYPEWRITER = REGISTRY.register("typewriter", () -> new TypewriterBlock());
    public static final DeferredBlock<Block> WALL_SHELF = REGISTRY.register("wall_shelf", () -> new WallShelfBlock());
    public static final DeferredBlock<Block> ANCIENT_TV_STAND = REGISTRY.register("ancient_tv_stand", () -> new AncientTVStandBlock());
    public static final DeferredBlock<Block> CEILING_LAMP = REGISTRY.register("ceiling_lamp", () -> new CeilingLampBlock());
    public static final DeferredBlock<Block> CHANDELIER = REGISTRY.register("chandelier", () -> new ChandelierBlock());
    public static final DeferredBlock<Block> CURTAIN_ROD = REGISTRY.register("curtain_rod", () -> new CurtainRodBlock());
    public static final DeferredBlock<Block> CURTAINS_1W = REGISTRY.register("curtains_1w", () -> new Curtains1wBlock());
    public static final DeferredBlock<Block> CURTAINS_1W_LONG = REGISTRY.register("curtains_1w_long", () -> new Curtains1wLongBlock());
    public static final DeferredBlock<Block> CURTAINS_LEFT = REGISTRY.register("curtains_left", () -> new CurtainsLeftBlock());
    public static final DeferredBlock<Block> CURTAINS_LEFT_LONG = REGISTRY.register("curtains_left_long", () -> new CurtainsLeftLongBlock());
    public static final DeferredBlock<Block> CURTAINS_RIGHT = REGISTRY.register("curtains_right", () -> new CurtainsRightBlock());
    public static final DeferredBlock<Block> CURTAINS_RIGHT_LONG = REGISTRY.register("curtains_right_long", () -> new CurtainsRightLongBlock());
    public static final DeferredBlock<Block> HANGING_SHELF = REGISTRY.register("hanging_shelf", () -> new HangingShelfBlock());
    public static final DeferredBlock<Block> OLD_BATHROOM_RADIATOR = REGISTRY.register("old_bathroom_radiator", () -> new OldBathroomRadiatorBlock());
    public static final DeferredBlock<Block> WALL_TELEPHONE = REGISTRY.register("wall_telephone", () -> new WallTelephoneBlock());
    public static final DeferredBlock<Block> TOILET = REGISTRY.register("toilet", () -> new ToiletBlock());
    public static final DeferredBlock<Block> WALL_LAMP_CANDLE = REGISTRY.register("wall_lamp_candle", () -> new WallLampCandleBlock());
    public static final DeferredBlock<Block> WALL_SHADE = REGISTRY.register("wall_shade", () -> new WallShadeBlock());
    public static final DeferredBlock<Block> WINDOW_BLINDS = REGISTRY.register("window_blinds", () -> new WindowBlindsBlock());
    public static final DeferredBlock<Block> WINDOW_BLINDS_LONG = REGISTRY.register("window_blinds_long", () -> new WindowBlindsLongBlock());
    private FarmhouseDecorationsModBlocks() {
    }
}
