package com.cookiecraftmods.farmhousedecorations.init;

import com.cookiecraftmods.farmhousedecorations.block.AncientTVStandBlock;
import com.cookiecraftmods.farmhousedecorations.block.CeilingLampBlock;
import com.cookiecraftmods.farmhousedecorations.block.ChandelierBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainRodBlock;
import com.cookiecraftmods.farmhousedecorations.block.Curtains1wBlock;
import com.cookiecraftmods.farmhousedecorations.block.Curtains1wLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsLeftBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsLeftLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsRightBlock;
import com.cookiecraftmods.farmhousedecorations.block.CurtainsRightLongBlock;
import com.cookiecraftmods.farmhousedecorations.block.HangingShelfBlock;
import com.cookiecraftmods.farmhousedecorations.block.OldBathroomRadiatorBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallTelephoneBlock;
import com.cookiecraftmods.farmhousedecorations.block.ToiletBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallLampCandleBlock;
import com.cookiecraftmods.farmhousedecorations.block.WallShadeBlock;
import com.cookiecraftmods.farmhousedecorations.block.WindowBlindsBlock;
import com.cookiecraftmods.farmhousedecorations.block.WindowBlindsLongBlock;

import com.cookiecraftmods.farmhousedecorations.FarmhouseDecorationsMod;
import com.cookiecraftmods.farmhousedecorations.block.*;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

public final class FarmhouseDecorationsModBlocks {
    public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(FarmhouseDecorationsMod.MODID);
    public static final DeferredBlock<Block> LIQUOR_CABINET = REGISTRY.registerBlock("liquor_cabinet", LiquorCabinetBlock::new);
    public static final DeferredBlock<Block> KEROSENE_LANTERN = REGISTRY.registerBlock("kerosene_lantern", KeroseneLanternBlock::new);
    public static final DeferredBlock<Block> ACOUSTIC_GUITAR = REGISTRY.registerBlock("acoustic_guitar", AcousticGuitarBlock::new);
    public static final DeferredBlock<Block> DOUBLE_BED = REGISTRY.registerBlock("double_bed", DoubleBedBlock::new);
    public static final DeferredBlock<Block> ANTIQUE_OVEN = REGISTRY.registerBlock("antique_oven", AntiqueOvenBlock::new);
    public static final DeferredBlock<Block> SINGLE_BED = REGISTRY.registerBlock("single_bed", SingleBedBlock::new);
    public static final DeferredBlock<Block> TALL_BOOKSHELF = REGISTRY.registerBlock("tall_bookshelf", TallBookshelfBlock::new);
    public static final DeferredBlock<Block> WINE_BOTTLE = REGISTRY.registerBlock("wine_bottle", WineBottleBlock::new);
    public static final DeferredBlock<Block> RED_WINE_BOTTLE = REGISTRY.registerBlock("red_wine_bottle", RedWineBottleBlock::new);
    public static final DeferredBlock<Block> CUCKOO_CLOCK = REGISTRY.registerBlock("cuckoo_clock", CuckooClockBlock::new);
    public static final DeferredBlock<Block> DINING_CHAIR = REGISTRY.registerBlock("dining_chair", DiningChairBlock::new);
    public static final DeferredBlock<Block> DINING_TABLE_SIDE = REGISTRY.registerBlock("dining_table_side", DiningTableSideBlock::new);
    public static final DeferredBlock<Block> DINING_TABLE_MIDDLE = REGISTRY.registerBlock("dining_table_middle", DiningTableMiddleBlock::new);
    public static final DeferredBlock<Block> DRESSER = REGISTRY.registerBlock("dresser", DresserBlock::new);
    public static final DeferredBlock<Block> NIGHT_STAND = REGISTRY.registerBlock("night_stand", NightStandBlock::new);
    public static final DeferredBlock<Block> PIANO = REGISTRY.registerBlock("piano", PianoBlock::new);
    public static final DeferredBlock<Block> PIANO_WITH_STOOL = REGISTRY.registerBlock("piano_with_stool", PianoWithStoolBlock::new);
    public static final DeferredBlock<Block> ROCKING_CHAIR = REGISTRY.registerBlock("rocking_chair", RockingChairBlock::new);
    public static final DeferredBlock<Block> ROUND_TABLE = REGISTRY.registerBlock("round_table", RoundTableBlock::new);
    public static final DeferredBlock<Block> STANDING_LAMP = REGISTRY.registerBlock("standing_lamp", StandingLampBlock::new);
    public static final DeferredBlock<Block> CHAINED_KEROSENE_LANTERN = REGISTRY.registerBlock("chained_kerosene_lantern", ChainedKeroseneLanternBlock::new);
    public static final DeferredBlock<Block> SOFA_LEFT = REGISTRY.registerBlock("sofa_left", SofaLeftBlock::new);
    public static final DeferredBlock<Block> SOFA_RIGHT = REGISTRY.registerBlock("sofa_right", SofaRightBlock::new);
    public static final DeferredBlock<Block> SOFA_MIDDLE = REGISTRY.registerBlock("sofa_middle", SofaMiddleBlock::new);
    public static final DeferredBlock<Block> TOOL_BOARD = REGISTRY.registerBlock("tool_board", ToolBoardBlock::new);
    public static final DeferredBlock<Block> WARDROBE = REGISTRY.registerBlock("wardrobe", WardrobeBlock::new);
    public static final DeferredBlock<Block> COAT_HANGER = REGISTRY.registerBlock("coat_hanger", CoatHangerBlock::new);
    public static final DeferredBlock<Block> WINE_GLASS = REGISTRY.registerBlock("wine_glass", WineGlassBlock::new);
    public static final DeferredBlock<Block> WORKBENCH = REGISTRY.registerBlock("workbench", WorkbenchBlock::new);
    public static final DeferredBlock<Block> KITCHEN_ANTIQUE_OVEN = REGISTRY.registerBlock("kitchen_antique_oven", KitchenAntiqueOvenBlock::new);
    public static final DeferredBlock<Block> KITCHEN_ANTIQUE_OVEN_DECORATED = REGISTRY.registerBlock("kitchen_antique_oven_decorated", KitchenAntiqueOvenDecoratedBlock::new);
    public static final DeferredBlock<Block> KITCHEN_COUNTER = REGISTRY.registerBlock("kitchen_counter", KitchenCounterBlock::new);
    public static final DeferredBlock<Block> KITCHEN_CORNER_CABINET = REGISTRY.registerBlock("kitchen_corner_cabinet", KitchenCornerCabinetBlock::new);
    public static final DeferredBlock<Block> KITCHEN_DRAWERS = REGISTRY.registerBlock("kitchen_drawers", KitchenDrawersBlock::new);
    public static final DeferredBlock<Block> KITCHEN_HALFWALL_SHELF = REGISTRY.registerBlock("kitchen_halfwall_shelf", KitchenHalfwallShelfBlock::new);
    public static final DeferredBlock<Block> KITCHEN_SINK = REGISTRY.registerBlock("kitchen_sink", KitchenSinkBlock::new);
    public static final DeferredBlock<Block> KITCHEN_WALL_CABINET = REGISTRY.registerBlock("kitchen_wall_cabinet", KitchenWallCabinetBlock::new);
    public static final DeferredBlock<Block> KITCHEN_CORNER_WALL_CABINET = REGISTRY.registerBlock("kitchen_corner_wall_cabinet", KitchenCornerWallCabinetBlock::new);
    public static final DeferredBlock<Block> KITCHEN_WALL_SHELF = REGISTRY.registerBlock("kitchen_wall_shelf", KitchenWallShelfBlock::new);
    public static final DeferredBlock<Block> BATHTUB = REGISTRY.registerBlock("bathtub", BathtubBlock::new);
    public static final DeferredBlock<Block> BATHROOM_CABINET = REGISTRY.registerBlock("bathroom_cabinet", BathroomCabinetBlock::new);
    public static final DeferredBlock<Block> BATHROOM_COUNTER = REGISTRY.registerBlock("bathroom_counter", BathroomCounterBlock::new);
    public static final DeferredBlock<Block> BATHROOM_SINK = REGISTRY.registerBlock("bathroom_sink", BathroomSinkBlock::new);
    public static final DeferredBlock<Block> BIG_BATHROOM_MIRROR = REGISTRY.registerBlock("big_bathroom_mirror", BigBathroomMirrorBlock::new);
    public static final DeferredBlock<Block> SMALL_BATHROOM_MIRROR = REGISTRY.registerBlock("small_bathroom_mirror", SmallBathroomMirrorBlock::new);
    public static final DeferredBlock<Block> TOWEL_HANGER = REGISTRY.registerBlock("towel_hanger", TowelHangerBlock::new);
    public static final DeferredBlock<Block> FRIDGE = REGISTRY.registerBlock("fridge", FridgeBlock::new);
    public static final DeferredBlock<Block> LAMP = REGISTRY.registerBlock("lamp", LampBlock::new);
    public static final DeferredBlock<Block> CIGAR_BOX = REGISTRY.registerBlock("cigar_box", CigarBoxBlock::new);
    public static final DeferredBlock<Block> GRAMOPHONE = REGISTRY.registerBlock("gramophone", GramophoneBlock::new);
    public static final DeferredBlock<Block> RADIATOR = REGISTRY.registerBlock("radiator", RadiatorBlock::new);
    public static final DeferredBlock<Block> PHONE = REGISTRY.registerBlock("phone", PhoneBlock::new);
    public static final DeferredBlock<Block> ANCIENT_TV_WITH_LEGS = REGISTRY.registerBlock("ancient_tv_with_legs", AncientTVWithLegsBlock::new);
    public static final DeferredBlock<Block> ANCIENT_TV = REGISTRY.registerBlock("ancient_tv", AncientTVBlock::new);
    public static final DeferredBlock<Block> COFFEE_TABLE = REGISTRY.registerBlock("coffee_table", CoffeeTableBlock::new);
    public static final DeferredBlock<Block> PILE_OF_BOOKS = REGISTRY.registerBlock("pile_of_books", PileOfBooksBlock::new);
    public static final DeferredBlock<Block> DESK = REGISTRY.registerBlock("desk", DeskBlock::new);
    public static final DeferredBlock<Block> DOOR_MAT = REGISTRY.registerBlock("door_mat", DoorMatBlock::new);
    public static final DeferredBlock<Block> SCREEN_CLOTH_1 = REGISTRY.registerBlock("screen_cloth_1", ScreenCloth1Block::new);
    public static final DeferredBlock<Block> SCREEN_CLOTH_2 = REGISTRY.registerBlock("screen_cloth_2", ScreenCloth2Block::new);
    public static final DeferredBlock<Block> SCREEN_WOOD_1 = REGISTRY.registerBlock("screen_wood_1", ScreenWood1Block::new);
    public static final DeferredBlock<Block> SCREEN_WOOD_2 = REGISTRY.registerBlock("screen_wood_2", ScreenWood2Block::new);
    public static final DeferredBlock<Block> RADIO = REGISTRY.registerBlock("radio", RadioBlock::new);
    public static final DeferredBlock<Block> RUG_1X_3 = REGISTRY.registerBlock("rug_1x_3", Rug1x3Block::new);
    public static final DeferredBlock<Block> RUG_3X_3 = REGISTRY.registerBlock("rug_3x_3", Rug3x3Block::new);
    public static final DeferredBlock<Block> SEASONING_RACK = REGISTRY.registerBlock("seasoning_rack", SeasoningRackBlock::new);
    public static final DeferredBlock<Block> TYPEWRITER = REGISTRY.registerBlock("typewriter", TypewriterBlock::new);
    public static final DeferredBlock<Block> WALL_SHELF = REGISTRY.registerBlock("wall_shelf", WallShelfBlock::new);
    public static final DeferredBlock<Block> ANCIENT_TV_STAND = REGISTRY.registerBlock("ancient_tv_stand", AncientTVStandBlock::new);
    public static final DeferredBlock<Block> CEILING_LAMP = REGISTRY.registerBlock("ceiling_lamp", CeilingLampBlock::new);
    public static final DeferredBlock<Block> CHANDELIER = REGISTRY.registerBlock("chandelier", ChandelierBlock::new);
    public static final DeferredBlock<Block> CURTAIN_ROD = REGISTRY.registerBlock("curtain_rod", CurtainRodBlock::new);
    public static final DeferredBlock<Block> CURTAINS_1W = REGISTRY.registerBlock("curtains_1w", Curtains1wBlock::new);
    public static final DeferredBlock<Block> CURTAINS_1W_LONG = REGISTRY.registerBlock("curtains_1w_long", Curtains1wLongBlock::new);
    public static final DeferredBlock<Block> CURTAINS_LEFT = REGISTRY.registerBlock("curtains_left", CurtainsLeftBlock::new);
    public static final DeferredBlock<Block> CURTAINS_LEFT_LONG = REGISTRY.registerBlock("curtains_left_long", CurtainsLeftLongBlock::new);
    public static final DeferredBlock<Block> CURTAINS_RIGHT = REGISTRY.registerBlock("curtains_right", CurtainsRightBlock::new);
    public static final DeferredBlock<Block> CURTAINS_RIGHT_LONG = REGISTRY.registerBlock("curtains_right_long", CurtainsRightLongBlock::new);
    public static final DeferredBlock<Block> HANGING_SHELF = REGISTRY.registerBlock("hanging_shelf", HangingShelfBlock::new);
    public static final DeferredBlock<Block> OLD_BATHROOM_RADIATOR = REGISTRY.registerBlock("old_bathroom_radiator", OldBathroomRadiatorBlock::new);
    public static final DeferredBlock<Block> WALL_TELEPHONE = REGISTRY.registerBlock("wall_telephone", WallTelephoneBlock::new);
    public static final DeferredBlock<Block> TOILET = REGISTRY.registerBlock("toilet", ToiletBlock::new);
    public static final DeferredBlock<Block> WALL_LAMP_CANDLE = REGISTRY.registerBlock("wall_lamp_candle", WallLampCandleBlock::new);
    public static final DeferredBlock<Block> WALL_SHADE = REGISTRY.registerBlock("wall_shade", WallShadeBlock::new);
    public static final DeferredBlock<Block> WINDOW_BLINDS = REGISTRY.registerBlock("window_blinds", WindowBlindsBlock::new);
    public static final DeferredBlock<Block> WINDOW_BLINDS_LONG = REGISTRY.registerBlock("window_blinds_long", WindowBlindsLongBlock::new);
    private FarmhouseDecorationsModBlocks() {
    }
}
