plugins {
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}

apply from: '../../gradle/common.gradle'

java.toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(project.java_version))

minecraft {
    mappings channel: 'official', version: project.minecraft_version

    runs {
        client {
        }

        server {
        }

        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                farmhouse_decorations {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}
